### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by bSkwared** [swgoh-utils/swgoh-comlink#1]
I updated some pages on the wiki that had broken fragment links. You can clone my wiki repo to pull the fixes over: https://github.com/bSkwared/swgoh-comlink.wiki.git

**Comment by munelear** [comment]
Thanks for doing this, sorry I didn't see it sooner.  I think I've applied all of the necessary updates now in the wiki.  Let me know in discord if you discover that's not the case.
