### ISSUE TITLE
Trying to use Endpoints to get data, but not working

### ISSUE THREAD

**Issue by rohid2000** [swgoh-utils/swgoh-comlink#7]
Good day! 

I've been trying to use your repo through Docker and I'm trying to use the /guild Endpoint and /player Endpoint, but when I execute the POST call for those 2 Endpoints, I keep getting an error: connect ECONNREFUSED. 

I think I've configured the variables right in Docker and in Postman. 

Could you guys help me?

Kind regards,

Rohid

**Comment by SdtBarbarossa** [comment]
This Problem is most likely caused by a missconfiguration.
Please contact us on Discord for a more direct Help.
https://discord.com/invite/5wqw9h5s

**Comment by rohid2000** [comment]
Thank you very much for responding so fast!

I'll see to the help once I'm back home from vacation.

Thank you again for the fast response and the help in advance!

With kind regards,

Rohid

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
